config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'
  resources :users do
    resources :my_pages, only:[:index, :new, :create]
  end
  resources :items do
    resources :orders, only:[:index, :create]
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :order
end

app/models/age.rb
class Age < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '20代未満' },
    { id: 3, name: '20~29歳' },
    { id: 4, name: '30~39歳' },
    { id: 5, name: '40~49歳' },
    { id: 6, name: '50~59歳' },
    { id: 7, name: '60~歳' },
  ]

  include ActiveHash::Associations
  has_many :my_pages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '陶磁器' },
    { id: 3, name: '織物' },
    { id: 4, name: '染物' },
    { id: 5, name: '木漆工' },
    { id: 6, name: '金工' },
    { id: 7, name: '石工' },
    { id: 8, name: '竹工' },
    { id: 9, name: '紙工' },
    { id: 10, name: '革工' },
    { id: 11, name: 'ガラス' },
    { id: 12, name: '彫刻' },
    { id: 13, name: '編組品' },
    { id: 14, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/delivery_day.rb
class DeliveryDay < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '2~3日で発送' },
    { id: 3, name: '4~7日で発送' },
    { id: 4, name: '8~日で発送' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord

  with_options presence: true do
    validates :product
    validates :content
    validates :category_id, numericality: { other_than: 1, message: "cant't be blank" }
    validates :postage_id, numericality: { other_than: 1, message: "cant't be blank" }
    validates :delivery_day_id, numericality: { other_than: 1, message: "can't be blank" }
    validates :price, numericality: { only_integer: true, less_than_or_equal_to: 9_999_999 }
    validates :images, length: { minimum: 1, maximum: 5 }
  end

  belongs_to :user
  has_many_attached :images, dependent: :destroy
  has_many :item_tags, dependent: :destroy
  has_many :tags, through: :item_tags
  has_one    :order, dependent: :destroy
  # has_many :reviews

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :postage
  belongs_to :delivery_day
end

app/models/item_form.rb
class ItemForm
  include ActiveModel::Model
  #ItemFormクラスのオブジェクトがItemモデルの属性を扱えるようにする
  attr_accessor :product, :content, :category_id, :postage_id,:delivery_day_id, :price, :user_id, :images,
                :tag_name,
                :id, :created_at, :updated_at

  with_options presence: true do
    validates :product
    validates :content
    validates :category_id, numericality: { other_than: 1, message: "cant't be blank" }
    validates :postage_id, numericality: { other_than: 1, message: "cant't be blank" }
    validates :delivery_day_id, numericality: { other_than: 1, message: "can't be blank" }
    validates :price, numericality: { only_integer: true, less_than_or_equal_to: 9_999_999 }
    validates :images, length: { minimum: 1, maximum: 5 }
    validates :user_id
  end

  def save
    item = Item.create(product: product, content: content, category_id: category_id, postage_id: postage_id, delivery_day_id: delivery_day_id, price: price, user_id: user_id, images: images)
    if tag_name.present?
      tag = Tag.where(tag_name: tag_name).first_or_initialize
      tag.save
      ItemTag.create(item_id: item.id, tag_id: tag.id)
    end
  end

  # controllerで呼び出したupdateメソッドから引数を受け取る
  def update(params, item)
    # 一度タグの紐づけを消す
    item.item_tags.destroy_all
    # params内のタグ情報削除
    tag_name = params.delete(:tag_name)
    
    tag = Tag.where(tag_name: tag_name).first_or_initialize if tag_name.present?

    tag.save if tag_name.present?
    item.update(params)
    ItemTag.create(item_id: item.id, tag_id: tag.id) if tag_name.present?
  end

  def destroy(params, item)
    item.destroy(params)
  end

end

app/models/item_tag.rb
class ItemTag < ApplicationRecord

  belongs_to :item
  belongs_to :tag, dependent: :destroy
end

app/models/my_page.rb
class MyPage < ApplicationRecord
  
  with_options presence: true do
    validates :name
    validates :profile
    validates :age_id, numericality: { other_than: 1}
    validates :prefecture_id, numericality: { other_than: 1}
    validates :image
  end

  # モデル登録時・place変更時に、緯度・経度データ登録・更新
  geocoded_by :place
  after_validation :geocode, if: :place_changed?

  belongs_to :user
  has_one_attached :image
  
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :age
  belongs_to :prefecture
end

app/models/order.rb
class Order < ApplicationRecord
  
  belongs_to :user
  belongs_to :item
  belongs_to :my_page
  has_one    :address, dependent: :destroy
end

app/models/order_address.rb
class OrderAddress
  include ActiveModel::Model
  attr_accessor :postcode, :prefecture_id, :city, :street, :building, :phone_number, :user_id, :item_id, :token

  with_options presence: true do
    validates :postcode, format: {with: /\A[0-9]{3}-[0-9]{4}\z/}
    validates :prefecture_id, numericality: { other_than: 1}
    validates :city
    validates :street
    validates :phone_number, numericality: {only_integer: true}, length: {minimum: 10, maximum: 11}
    validates :user_id
    validates :item_id
    validates :token
  end

  def save
    order = Order.create(user_id: user_id, item_id: item_id)
    Address.create(postcode: postcode, prefecture_id: prefecture_id, city: city, street: street, building: building, phone_number: phone_number, order_id: order.id)
  end
end

app/models/postage.rb
class Postage < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '送料別' },
    { id: 3, name: '送料込み' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' }, { id: 2, name: '北海道' }, { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' }, { id: 5, name: '宮城県' }, { id: 6, name: '秋田県' },
    { id: 7, name: '山形県' }, { id: 8, name: '福島県' }, { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' }, { id: 11, name: '群馬県' }, { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' }, { id: 14, name: '東京都' }, { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' }, { id: 17, name: '富山県' }, { id: 18, name: '石川県' },
    { id: 19, name: '福井県' }, { id: 20, name: '山梨県' }, { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' }, { id: 23, name: '静岡県' }, { id: 24, name: '愛知県' },
    { id: 25, name: '三重県' }, { id: 26, name: '滋賀県' }, { id: 27, name: '京都府' },
    { id: 28, name: '大阪府' }, { id: 29, name: '兵庫県' }, { id: 30, name: '奈良県' },
    { id: 31, name: '和歌山県' }, { id: 32, name: '鳥取県' }, { id: 33, name: '島根県' },
    { id: 34, name: '岡山県' }, { id: 35, name: '広島県' }, { id: 36, name: '山口県' },
    { id: 37, name: '徳島県' }, { id: 38, name: '香川県' }, { id: 39, name: '愛媛県' },
    { id: 40, name: '高知県' }, { id: 41, name: '福岡県' }, { id: 42, name: '佐賀県' },
    { id: 43, name: '長崎県' }, { id: 44, name: '熊本県' }, { id: 45, name: '大分県' },
    { id: 46, name: '宮崎県' }, { id: 47, name: '鹿児島県' }, { id: 48, name: '沖縄県' },
    { id: 49, name: 'ForeignCountry' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/tag.rb
class Tag < ApplicationRecord

  validates :tag_name, uniqueness: { case_sensitive: true }, presence: true

  has_many :item_tags
  has_many :items, through: :item_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze

  validates :nickname, presence: true
  validates :password, format: { with: PASSWORD_REGEX }
  validates :user_check_id, numericality: { other_than: 1, message: "can't be blank" }

  has_many :items
  has_many :orders
  has_one :my_page
  
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user_check

end

app/models/user_check.rb
class UserCheck < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '出品者' },
    { id: 3, name: '購入者' },
  ]

  include ActiveHash::Associations
  has_many :users
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/my_pages_helper.rb
module MyPagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OriginalApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# Googleフォント %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/earlyaccess/hannari.css" rel="stylesheet">

    <%# PAY.JP %>
    <script type="text/javascript" src="https://js.pay.jp/v2/pay.js"></script>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>

  </head>

  <body>

    <%= yield %>

  </body>

</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("top_logo.png", class:"second-icon"), "/" %>
</header>

app/views/shared/_toppage.html.erb
<%# CSS・・・assets/stylesheets/toppage.css %>

<title>民藝 × 丁寧な暮らし</title>

<div class="slide">
  <div class="bgImg srcImage1"></div>
  <div class="bgImg srcImage2"></div>
  <div class="bgImg srcImage3"></div>
  <div class="bgImg srcImage4"></div>

  <div class="main">
    <%# アイコン %>
    <div class='search-bar-contents'>
      <%= link_to image_tag("top_logo.png", class:"top-icon"), "/" %>
    </div>

    <%# カテゴリ %>
    <div class='nav'>
      <ul class='lists-left'>
        <li><%= link_to 'カテゴリー', "#", class: "category-list" %></li>
        <li><%= link_to 'ブランド', "#", class: "brand-list" %></li>
      </ul>

      <%# ユーザー機能 %>

      <ul class='lists-right'>  
        <% if user_signed_in? %>
          <li><%= link_to current_user.nickname, user_my_pages_path(current_user.id), class: "user-nickname" %></li>
            <% if current_user.user_check_id == 2 %>
              <li><%= link_to '出品する', new_item_path, class: "purchase-list" %></li>
            <% end %>
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
        <% else %>
          <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
          <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
        <% end %>
      </ul>

      <%# 検索欄 %>

      <form class="search-form" action="#">
        <input class='input-box' placeholder='キーワードから探す'>
        <button class="search-button">
          <%# <%= image_tag "search.png", class:"search-icon" %> 
        </button>
      </form>

    </div>
  </div>
</div>