config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'
  resources :users do
    resources :my_pages, only:[:index, :new, :create]
  end
  resources :items do
    resources :orders, only:[:index, :create]
  end

end

app/models/item.rb
class Item < ApplicationRecord

  with_options presence: true do
    validates :product
    validates :content
    validates :category_id, numericality: { other_than: 1, message: "cant't be blank" }
    validates :postage_id, numericality: { other_than: 1, message: "cant't be blank" }
    validates :delivery_day_id, numericality: { other_than: 1, message: "can't be blank" }
    validates :price, numericality: { only_integer: true, less_than_or_equal_to: 9_999_999 }
    validates :images, length: { minimum: 1, maximum: 5 }
  end

  belongs_to :user
  has_many_attached :images, dependent: :destroy
  has_many :item_tags, dependent: :destroy
  has_many :tags, through: :item_tags
  has_one    :order, dependent: :destroy
  # has_many :reviews

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :postage
  belongs_to :delivery_day
end

app/models/item_form.rb
class ItemForm
  include ActiveModel::Model
  #ItemFormクラスのオブジェクトがItemモデルの属性を扱えるようにする
  attr_accessor :product, :content, :category_id, :postage_id,:delivery_day_id, :price, :user_id, :images,
                :tag_name,
                :id, :created_at, :updated_at

  with_options presence: true do
    validates :product
    validates :content
    validates :category_id, numericality: { other_than: 1, message: "cant't be blank" }
    validates :postage_id, numericality: { other_than: 1, message: "cant't be blank" }
    validates :delivery_day_id, numericality: { other_than: 1, message: "can't be blank" }
    validates :price, numericality: { only_integer: true, less_than_or_equal_to: 9_999_999 }
    validates :images, length: { minimum: 1, maximum: 5 }
    validates :user_id
  end

  def save
    item = Item.create(product: product, content: content, category_id: category_id, postage_id: postage_id, delivery_day_id: delivery_day_id, price: price, user_id: user_id, images: images)
    if tag_name.present?
      tag = Tag.where(tag_name: tag_name).first_or_initialize
      tag.save
      ItemTag.create(item_id: item.id, tag_id: tag.id)
    end
  end

  # controllerで呼び出したupdateメソッドから引数を受け取る
  def update(params, item)
    # 一度タグの紐づけを消す
    item.item_tags.destroy_all
    # params内のタグ情報削除
    tag_name = params.delete(:tag_name)
    
    tag = Tag.where(tag_name: tag_name).first_or_initialize if tag_name.present?

    tag.save if tag_name.present?
    item.update(params)
    ItemTag.create(item_id: item.id, tag_id: tag.id) if tag_name.present?
  end

  def destroy(params, item)
    item.destroy(params)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy]
  before_action :move_to_index, only: [:edit, :update, :destroy]
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.all
  end

  def new
    @item_form = ItemForm.new
    @user = current_user
    unless @user.my_page.present?
      redirect_to new_user_my_page_path(user_id: current_user.id)
    end
      
  end

  def create
    @item_form = ItemForm.new(item_form_params)
    if @item_form.valid?
      @item_form.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @my_page = @item.user.my_page
  end

  def edit
    item_attributes = @item.attributes
    @item_form = ItemForm.new(item_attributes)
    @item_form.tag_name = @item.tags.first&.tag_name
  end

  def update
    @item_form = ItemForm.new(item_form_params)
    @item_form.images ||= @item.images.blobs
    
    if @item_form.valid?
      @item_form.update(item_form_params, @item)
      redirect_to "/items/#{@item.id}"
    else
      render :edit
    end
  end

  def destroy
    if current_user.id == @item.user_id
      @item.destroy
      redirect_to root_path
    end
  end

  private
  
  def item_form_params
    params.require(:item_form).permit(:product, :content, :category_id, :postage_id, :delivery_day_id, :price, :tag_name, {images: []}).merge(user_id: current_user.id)
  end

  def move_to_index
    @item = Item.find(params[:id])
    if current_user.id != @item.user_id
      redirect_to root_path
    end
  end

  def set_item
    @item = Item.find(params[:id])
  end
  
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_concept.html.erb
<div class="top-concept">

<%# 全体 %>
<div class="concept-wrap">
  
  <%# 背景動画 %>
  <div class="layer">
    <video id="bg-video" autoplay loop muted>
      <source src="/videos/sunset.mp4" type="video/mp4">
    </video>
  </div>


  <%# 丸三つ部分 %>
  <div class="concept-circles">

    <%# 丸各エリア %>
      <div class="circle", id="circles">
        <div class="circle_text"><h1>知る</h1></div>
      </div>
      <div class="circle">
        <div class="circle_text"><h1>使う</h1></div>
      </div>
      <div class="circle">
        <div class="circle_text"><h1>伝える</h1></div>
      </div>
    </div>

  </div>

</div>

<%# コンセプト詳細部分 %>
<div class="concept-inner_contents">

  <%# コンセプト各エリア %>
  <div class="contents_area">

    <div class="contetns_area__title">
      <h1>「美は生活の中にある」</h1>
    </div>

    <span>
    <p>民藝品とは「一般の民衆が日々の生活に必要とする品」という意味で</p>
    <p>私たちの身近にあったものでした</p><br>
    <p>たくさんのものに囲まれて　私たちが忘れてしまった</p>
    <p>本当の豊かさ 伝統の美しさを</p>
    <br><p>あなたの生活の中で、見つけてみませんか？</p>
    </span>
    
  </div>
  </div>

</div>

app/views/items/edit.html.erb
<%= render "shared/second-header"%>

<div class="items-sell-contents">

  <div class='form-header'>
    <h1 class='form-header-text'>商品出品登録</h1>
    <p class="form-acounthelp"><span class="must">*</span> は必須項目です</p>
  </div>


    <%= form_with model: @item_form, url: item_path(@item.id), method: :patch, id: 'new_item', local: true do |f| %>

    <%# エラー表示部分 %>
    <div class='error-flash-message'>
      <%= render 'shared/error_messages', model: f.object %>
    </div>
    
    <%# 商品画像 %>
    <div class="img-upload">
      
      <div class="image-field">
        <div id="previews"></div>
        <div class="click-upload">
    
        </div>
      </div>
    </div>
    
    <%# /商品画像 %>

    <%# 画像以下 %>

    <div class="new-items">


      <%# 画像 %>
      <div class="form-item-new">
        <div class="weight-bold-text">
          商品画像<span class="must">*</span>
        </div>
        <%= f.file_field :images, name: 'item_form[images][]', data: {index: 0}, class: "preview-img" %>
      </div>


      <%# 商品名 %>
      <div class="form-item-new">
        <div class="weight-bold-text">
          商品名<span class="must">*</span>
        </div>
        <%= f.text_area :product, class: "new-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      </div>

      <%# 商品説明 %>
      <div class="form-item-new">
        <div class="weight-bold-text">
          商品の説明<span class="must">*</span>
        </div>
        <%= f.text_area :content, class:"new-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>
      </div>

      <%# カテゴリー %>
      <div class="form-item-new">
        <div class="weight-bold-text">
          カテゴリー<span class="must">*</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      </div>

      <%# タグ %>
      <div class="form-item-new">
        <div class="weight-bold-text">
          商品タグ（例：キッチン、冠婚葬祭、プレゼント）
        </div>
        <%= f.text_field :tag_name, placeholder: 'タグを追加', class:"tag-box" %>
      </div>

      <%# 送料 %>
      <div class="form-item-new">
        <div class="weight-bold-text">
          配送料の負担<span class="must">*</span>
        </div>
        <%= f.collection_select(:postage_id, Postage.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
      </div>

      <%# 発送日 %>
      <div class="form-item-new">
        <div class="weight-bold-text">
          発送までの日<span class="must">*</span>
        </div>
        <%= f.collection_select(:delivery_day_id, DeliveryDay.all, :id, :name, {}, {class:"select-box", id:"item-scheduled-delivery"}) %>
      </div>


      <%# 販売価格 %>
      <div class="form-item-new">
        <div class="weight-bold-text">
          価格<span class="must">*</span>
        </div>
        <span class="sell-yen">¥</span>
        <%= f.text_field :price, class:"new-item-price", id:"item-price", placeholder:"例）1500" %>
      </div>

    
      <%# 下部ボタン %>
      <div class="sell-btn-contents">
        <%= f.submit "変更する" ,class:"sell-btn" %>
        <div>
          <%=link_to 'もどる', "/items/#{@item.id}", class:"back-btn" %>
        </div>
      </div>
      <%# /下部ボタン %>


    </div>

  <% end %>

</div>

app/views/items/index.html.erb
<%= render "shared/toppage"%>


<%# 全体 %>
<div class="top-main">

  <%# コンセプト %>
    <%= render "concept"%>

  <%# アイテム一覧全体 %>
  <div class="line-up">
    <%# タイトル %>
    <div class="line-up-title">
      <div class="line-up-title_text">
        <h1>Line Up</h1>
      </div>
    </div>
    
    <%# アイテムひっくるめてエリア %>
    <div class="content-items">

      <%# アイテム一個ずつエリア %>
      <div class="content-item">

      <% if @items != [] %>

        <% @items.each do |item| %>

          <div class="posted-content">

            <%# 代表一枚 %>
              <div class="top-main-item_area">
                <%= link_to image_tag(item.images[0], class: "main-image"), "/items/#{item.id}" %><br>
              </div>
              <%# その他 %>
              <div class="posted-content-others">
                <% item.images[1..-1].each do |image| %>
                  <div class="other-images">
                    <%= image_tag image, class: "other-image" %>
                  </div>
                <% end %>
              </div>

            <%# 商品情報 %>
            <div class="top-item-text">

              <%# 商品名 %>
              <div class="top-item-name">
                <h3><%= item.product %></h3>
              </div>

              <%# 金額 %>
              <div class="top-item-price">
                <% if item.order == nil %>
                  <p>￥<%= number_with_delimiter(item.price) %></p>
                  <span><%= item.postage.name %></span>
                <% else %>
                  <span>sold out</span>
                <% end %>
              </div>

              <%# タグ %>
              <%# <div>
                <div><%= item.tags.first&.tag_name</div> %>
              <%# </div> %> 

            </div>

          </div>
        <% end %>
      <% end %>

      </div>
    
    </div>

  </div>

</div>

app/views/items/new.html.erb
<%= render "shared/second-header"%>

<div class="items-sell-contents">

  <div class='form-header'>
    <h1 class='form-header-text'>商品出品登録</h1>
    <p class="form-acounthelp"><span class="must">*</span> は必須項目です</p>
  </div>

  <%= form_with model: @item_form, url: items_path, method: :post, id: 'new_item', local: true do |f| %>

    <%# エラー表示部分 %>
    <div class='error-flash-message'>
      <%= render 'shared/error_messages', model: f.object %>
    </div>
    
    <%# 商品画像 %>
    <div class="img-upload">
      
      <div class="image-field">
        <div id="previews"></div>
        <div class="click-upload">
    
        </div>
      </div>
    </div>
    
    <%# /商品画像 %>

    <%# 画像以下 %>

    <div class="new-items">


      <%# 画像 %>
      <div class="form-item-new">
        <div class="weight-bold-text">
          商品画像（実際に生活の中で使われている写真を投稿してください）<span class="must">*</span>
        </div>
        <%= f.file_field :images, name: 'item_form[images][]', data: {index: 0}, class: "preview-img" %>
      </div>


      <%# 商品名 %>
      <div class="form-item-new">
        <div class="weight-bold-text">
          商品名<span class="must">*</span>
        </div>
        <%= f.text_area :product, class: "new-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      </div>

      <%# 商品説明 %>
      <div class="form-item-new">
        <div class="weight-bold-text">
          商品の説明<span class="must">*</span>
        </div>
        <%= f.text_area :content, class:"new-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>
      </div>

      <%# カテゴリー %>
      <div class="form-item-new">
        <div class="weight-bold-text">
          カテゴリー<span class="must">*</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      </div>

      <%# タグ %>
      <div class="form-item-new">
        <div class="weight-bold-text">
          商品タグ（例：キッチン、冠婚葬祭、プレゼント）
        </div>
        <%= f.text_field :tag_name, placeholder: 'タグを追加', class:"tag-box" %>
      </div>

      <%# 送料 %>
      <div class="form-item-new">
        <div class="weight-bold-text">
          配送料の負担<span class="must">*</span>
        </div>
        <%= f.collection_select(:postage_id, Postage.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
      </div>

      <%# 発送日 %>
      <div class="form-item-new">
        <div class="weight-bold-text">
          発送までの日<span class="must">*</span>
        </div>
        <%= f.collection_select(:delivery_day_id, DeliveryDay.all, :id, :name, {}, {class:"select-box", id:"item-scheduled-delivery"}) %>
      </div>


      <%# 販売価格 %>
      <div class="form-item-new">
        <div class="weight-bold-text">
          価格<span class="must">*</span>
        </div>
        <span class="sell-yen">¥</span>
        <%= f.text_field :price, class:"new-item-price", id:"item-price", placeholder:"例）1500" %>
      </div>


      <%# 下部ボタン %>
      <div class="sell-btn-contents">
        <%= f.submit "出品する" ,class:"sell-btn" %>
        <div><%= link_to 'もどる', root_path, class:"back-btn" %></div>
      </div>

    </div>  
    <%# /下部ボタン %>

  <% end %>

  
</div>

app/views/items/show.html.erb
<%= render "shared/second-header"%>

<%# 全体 %>
<div class="show-wrap">

<%# アイテム部分全体 %>
<div class="show-wrap-inner">

  <%# 画像部分全体 %>
  <div class="show-images-area">

    <%# 代表一枚 %>
    <div class="show-image">
      <%= image_tag @item.images[0], class: "show-main_image" %><br>
    </div>
    <%# その他 %>
    <div class="show-other_images-area">
      <% @item.images[1..-1].each do |image| %>
        <div class="other-image-box">
          <%= image_tag image, class: "show-other_image" %>
        </div>
      <% end %>
    </div>

  </div>

  <%# テキスト部分全体 %>
  <div class="show-text-area">

    <div class="show-text">

      <%# 商品名 %>
      <div class="show-product">
        <h1><%= @item.product %></h1>
        <h2><%= @my_page.bland %></h2>
      </div>

      <%# 商品価格、送料 %>
      <div class="show-price">
        ￥<%= number_with_delimiter(@item.price) %>
        <% if @item.order != nil %>
          <span class="sold-out">( sold out )</span>
        <% end %>
      <div class="show-postage">
        <%= @item.postage.name %></span>
      </div>
      </div>

      <%# 商品説明 %>
      <div class="show-content">
        <%= @item.content %>
      </div>

      <%# 購入ボタンほか %>
      <div class="item-control">
        <% if user_signed_in? && current_user.id == @item.user_id %>
        
            <% if @item.order == nil %>
              <div class="btn-box">
                <%= link_to '編集する', edit_item_path(@item.id), method: :get, class: "creator-btn" %>
              </div>
              <div class="btn-box">
                <%= link_to '削除する', item_path(@item.id), method: :delete, class:"creator-btn", id: "delete-btn" %>
              </div>
            <% else %>
              <div class="btn-box">
                <%= link_to '削除する', item_path(@item.id), method: :delete, class:"creator-btn", id: "delete-btn" %>
              </div>
            <% end %>
        <% elsif @item.order == nil %>
          <div class="btn-box">
            <%= link_to '購入する', item_orders_path(@item.id), method: :get, class: "buyer-btn" %>
          </div>
        <% else %>
          <div class="btn-box">
            <div class="sold-out-btn"><p>sold out</p><div>
          </div>
        
        <% end %>
      </div>

      <%# 配達予想 %>
      <div class="show-delivery">
        <%= image_tag "haisou.png", :size => "80x80" %>
        <span><%= @item.delivery_day.name %></span>
      </div>
      
      <%# タグ %>
      <%# <div>
        <%= @item.tags.first&.tag_name %>
      <%# </div>  %>

      <%# 出品者 %>
      <div class="show-content">
        <div class="show-creator-atelier">
          <%= link_to "#{@my_page.atelier}", user_my_pages_path(@item.user.id) %>
        </div>
        <div class="show-creator-address">
          <%= @my_page.prefecture.name %>
          <%= @my_page.place %>
          <br><br><%= link_to @my_page.website %><br>
      </div>

    </div>
  </div>

</div>
</div>